//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.ExtraordinaryRepairs1 = new HashSet<ExtraordinaryRepairs>();
            this.PreventiveRepairs = new HashSet<PreventiveRepairs>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> fk_TypeEquipment { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> DateOfCommission { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> ResidualPrice { get; set; }
        public short PercentageOfWear { get; set; }
        public string fk_Work_NotWork { get; set; }
        public string RequiredRepairs { get; set; }

        private DateTime dateDefaultPreventive = new DateTime(1900, 01, 01);
        public Nullable<System.DateTime> PreventiveMaintenance
        {
            get => dateDefaultPreventive.Date;
            set
            {
                dateDefaultPreventive =(DateTime)value;
            }
        }

        private DateTime dateDefaultExtraordinary = new DateTime(1900, 01, 01);
        public Nullable<System.DateTime> ExtraordinaryRepairs 
        { get=> dateDefaultExtraordinary.Date;
            set 
            { 
                dateDefaultExtraordinary = (DateTime)value;
            } 
        }
    
        public virtual TypeEquipment TypeEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraordinaryRepairs> ExtraordinaryRepairs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreventiveRepairs> PreventiveRepairs { get; set; }
    }
}
