//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraordinaryRepairs
    {
        public int Id { get; set; }
        public Nullable<int> fk_EquipmentId { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Price { get; set; }
        public string Operation { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
